use crate::{
    Melody,
    note::{Duration::*, Pitch::*},
};
pub const TEMPO: u16 = 120;

pub const MELODY: Melody = Melody(&[
    (E4, Quarter),
    (E4, Quarter),
    (F4, Quarter),
    (G4, Quarter),
    (G4, Quarter),
    (F4, Quarter),
    (E4, Quarter),
    (D4, Quarter),
    (C4, Quarter),
    (C4, Quarter),
    (D4, Quarter),
    (E4, Quarter),
    (E4, Dotted(4)),
    (D4, Eighth),
    (D4, Half),
    (E4, Quarter),
    (E4, Quarter),
    (F4, Quarter),
    (G4, Quarter),
    (G4, Quarter),
    (F4, Quarter),
    (E4, Quarter),
    (D4, Quarter),
    (C4, Quarter),
    (C4, Quarter),
    (D4, Quarter),
    (E4, Quarter),
    (D4, Dotted(4)),
    (C4, Eighth),
    (C4, Half),
]);
