use crate::{
    Melody,
    note::{Duration::*, Pitch::*},
};

pub const TEMPO: u16 = 72;

pub const MELODY: Melody = Melody(&[
    (C4, Quarter),
    (C4, Quarter),
    (G4, Quarter),
    (G4, Quarter),
    (A4, Quarter),
    (A4, Quarter),
    (G4, Half),
    (F4, Quarter),
    (F4, Quarter),
    (E4, Quarter),
    (E4, Quarter),
    (D4, Quarter),
    (D4, Quarter),
    (C4, Half),
    (G4, Quarter),
    (G4, Quarter),
    (F4, Quarter),
    (F4, Quarter),
    (E4, Quarter),
    (E4, Quarter),
    (D4, Half),
    (G4, Quarter),
    (G4, Quarter),
    (F4, Quarter),
    (F4, Quarter),
    (E4, Quarter),
    (E4, Quarter),
    (D4, Half),
    (C4, Quarter),
    (C4, Quarter),
    (G4, Quarter),
    (G4, Quarter),
    (A4, Quarter),
    (A4, Quarter),
    (G4, Half),
    (F4, Quarter),
    (F4, Quarter),
    (E4, Quarter),
    (E4, Quarter),
    (D4, Quarter),
    (D4, Quarter),
    (C4, Half),
]);
